window.jmn = {
  Y: {},
  videoList: [
    { title: "Pincha mayurászana slow flow", youtube: "_2LJOx4wLsE", id: 31 },
    {
      title: "Tavaszi megújulás - astanga alapú óra",
      youtube: "S3PGbCz4108",
      id: 56,
    },
    { title: "Belső erő - a légzés ereje", youtube: "YsD3O7dg6iQ", id: 68 }].concat([

      { title: "Online jóga óra 2020.03.16", youtube: "_gnrBDorOmo", id: 1 },
      { title: "Online jóga épített óra", youtube: "UhUWu7xtJiM", id: 2 },
      { title: "Flowjóga ekapada galavászana", youtube: "qjC8kCXW5nI", id: 3 },
      { title: "Épített flowjóga", youtube: "uu5vYFQbBy0", id: 4 },
      { title: "Flow jóga légzőgyakorlatokkal", youtube: "w91uoIBek14", id: 5 },
      { title: "Flow jóga", youtube: "hJek7qSx9eI", id: 6 },
      { title: "Online jóga ladder flow", youtube: "SMi0po2ZdoE", id: 7 },
      { title: "Astanga alapú jóga óra", youtube: "Q3Qe9Y9cj6k", id: 8 },
      {
        title: "Online jógaóra kéztőalagút szindróma",
        youtube: "F7r8mMJUed8",
        id: 9,
      },
      { title: "Tematikus óra: padmászana", youtube: "lU3sfvfpx2c", id: 10 },
      { title: "Ladder flow", youtube: "c6QOrf7r2lE", id: 11 },
      { title: "Épített, hullámzó jóga flow", youtube: "-HfCdCT5xww", id: 12 },
      { title: "Slow flow", youtube: "dIoG3dEv3QI", id: 13 },
      // { title: '14. slow ladder flow', youtube: 'WfAgenbbHsQ', id: 14 },
      // { title: '15. térdelésmentes flow', youtube: 'fc6doVdJxJE', id: 15 },
      {
        title: "Slow flow hétfő esti belassulás",
        youtube: "_w5j7uCmWiQ",
        id: 16,
      },
      // { title: '17. slow flow földüdvözlettel', youtube: '_2VON0I90ZQ', id: 17 },
      // { title: '18. slow flow skorpióval', youtube: 'JKFjL6I7OBk', id: 18 },
      // { title: '19. flow jóga svarga dvidászana', youtube: 'nfFHdWjwYCI', id: 19 },
      // { title: '20. csavarások, ekapada koundinyászana', youtube: 'x5amGcrU3EE', id: 20 },
      // { title: '21. hátrahajlások', youtube: 'Z-NDibBmi8k', id: 21 },
      { title: "Mély erő", youtube: "I4gfhB_y0iw", id: 22 },
      { title: "Ladder flow", youtube: "o5kpNSxHD-o", id: 23 },
      { title: "Mély nyitás", youtube: "wGcVX0H_ncE", id: 24 },
      { title: "Ladder flow mátrix", youtube: "lAmscFix6aM", id: 25 },
      { title: "Előrehajlások földüdvözlettel", youtube: "xPJq0rTujEQ", id: 26 },
      {
        title: "Álló napüdvözletek",
        youtube: "Qx1tnmMB-cs",
        id: 27,
        sample: true,
      },
      {
        title: "Ladder flow bukfenc",
        youtube: "7K-7Vw7aShc",
        id: 28,
        sample: true,
      },
      {
        title: "Fasciális szemlélet - elülső és hátulsó láncolat",
        youtube: "VL2_7jKPv8E",
        id: 29,
      },

      { title: "Eszközös jógaóra téglával", youtube: "2-cdiIGsbZY", id: 30 },

      { title: "Punch rose flow jóga", youtube: "UAWEE7zmCho", id: 32 },
      { title: "Térdelésmentes flow jóga", youtube: "j6F46wDQk8s", id: 33 },
      { title: "Ekapada bakászana flow", youtube: "NMY334y4tg4", id: 34 },
      { title: "Grasshopper flow", youtube: "-6Tax7kr9Yc", id: 35 },
      {
        title: "Gyertya flow, ekapada galavászana",
        youtube: "pHdSCtkKxx8",
        id: 36,
      },

      { title: "Kartámaszos gyakorlatok", youtube: "adwo0Xwn2mM", id: 37 },
      { title: "Kamatkarászana flow", youtube: "wJAP9PifcQw", id: 38 },
      { title: "Mooladhara csakra", youtube: "OW3-xCXCyXI", id: 39 },
      { title: "Svadhisthana csakra", youtube: "9OYEGfIIwuw", id: 40 },
      { title: "Manipura csakra", youtube: "ftdAt0i0R88", id: 41 },
      { title: "Anahata csakra", youtube: "grlCXl2L4TY", id: 42 },
      { title: "Felső csakrák", youtube: "23XyMjeracc", id: 43 },
      {
        title: "Tematikus flowjóga órák: kurmászana",
        youtube: "OJGplXx0hYw",
        id: 44,
      },
      {
        title: "Tematikus flowjóga órák: hanumanászana",
        youtube: "VVsd6RZGz1M",
        id: 45,
      },
      {
        title: "Tematikus flowjóga órák: urdhva dhanurászana",
        youtube: "lhHTeOszAxA",
        id: 46,
      },
      {
        title: "Tematikus flowjóga órák: ekapada galavászana",
        youtube: "V7tc6O__FXI",
        id: 47,
      },
      {
        title: "Tematikus flowjóga órák: padmászana",
        youtube: "9F3qynsnogU",
        id: 48,
      },

      { title: "Ébredj! Emelkedj szívnyitó óra", youtube: "q4a4Wmna4nE", id: 49 },
      { title: "Ébredj! Nyiss! csípőnyitás", youtube: "eImRkobcqqc", id: 50 },
      { title: "Ébredj! Bízz a saját erődben", youtube: "e4zKuviVUeo", id: 51 },
      { title: "Ébredj! Cselekedj!", youtube: "rYDeity91K0", id: 52 },
      { title: "Ébredj! Áramolj ladder flow", youtube: "nFWpSuSdED4", id: 53 },

      {
        title: "Tavaszi megújulás - Slow flow uddzsáj légzéssel",
        youtube: "RIJlvd_XaDw",
        id: 54,
      },
      {
        title: "Tavaszi megújulás - Mátra ladder flow",
        youtube: "BNLYa-CsyUA",
        id: 55,
      },

      { title: "Tavaszi megújulás - flow+yin", youtube: "5U_M1z63r4Q", id: 57 },

      {
        title: "Last minute - egyensúly és stabilitás",
        youtube: "RIJlvd_XaDw",
        id: 58,
      },
      {
        title: "Last minute - mély erő a hátrahajlásban",
        youtube: "3qTQhorWRJw",
        id: 59,
      },
      {
        title: "Last minute - fordított testhelyzetek",
        youtube: "0ctDXR-9ub8",
        id: 60,
      },
      { title: "Last minute - slow ladder flow", youtube: "vnFagZJYcms", id: 61 },
      {
        title: "Last minute - Terápiás eszközök használata",
        youtube: "UzMXZzNNGg4",
        id: 62,
      },

      {
        title: "Tetőtől talpig átmozgató slowflow",
        youtube: "grKdykA_KP0",
        id: 63,
      },
      { title: "Stabilitás flow", youtube: "COzAhfHvsw0", id: 64 },
      { title: "Elengedés", youtube: "lwIxa5VtEfE", id: 65 },
      { title: "Úszás a boldogságban", youtube: "M3F5vBZzxWo", id: 66 },
      { title: "Édes kis nyújtózás", youtube: "_qKD4DJwkn0", id: 67 },

      { title: "A belső csend ereje", youtube: "tzDfpAhKzRU", id: 69 },
      { title: "Belső erő - a szív ereje", youtube: "ACvvOygK-LY", id: 70 },
      {
        title: "Teremts békét magadban - Középpont",
        youtube: "tCW1KaRf7Pg",
        id: 71,
      },
      {
        title: "Teremts békét magadban - tisztelet",
        youtube: "_9DWF43jMNM",
        id: 72,
      },
      {
        title: "Teremts békét magadban - teremtés",
        youtube: "fimFxXGH3AY",
        id: 73,
      },
      {
        title: "Teremts békét magadban - harmónia",
        youtube: "9uAlWwQQKuk",
        id: 74,
      },
      {
        title: "Teremts békét magadban - bízalom",
        youtube: "DouUsR46IxA",
        id: 75,
      },
      { title: "Emelkedj - jelenlét", youtube: "vZIGw8YeWiE", id: 76 },
      { title: "Emelkedj - belső tűz", youtube: "wfWW5F0M7Gg", id: 77 },
      { title: "Emelkedj - szívüdvözlet", youtube: "eEhj0Uqb1yg", id: 78 },
      { title: "Emelkedj - szárnyalj", youtube: "cxWKQCwUCj8", id: 79 },
      { title: "Emelkedj - ég és föld", youtube: "QlzgQwtplZ4", id: 80 },
      { title: "Fascia a jógában 1. Hátulsó láncolat", youtube: "cp2RRVHLwp0 ", id: 81, ext:'webp'},
      { title: "Fascia a jógában 2. Elülső láncolat", youtube: "CT9BYwKNHBU", id: 82, ext:'webp'},
      { youtube: "NuXbYNQzZ0U", title: "Fascia a jógában 3. Oldalsó láncolat", id: 83, ext:'webp'},
      { youtube: "lRGmWBAlkQI", title: "Fascia a jógában 4. Spirális láncolat", id: 84, ext:'webp'},
      { youtube: "aV3Y2pA2AeM", title: "Fascia a jógában 5. Mély nyitás", id: 85, ext:'webp'},
      { youtube: "F9Mg6NdIt_4", title: "Fascia a jógában 6. Mély erő", id: 86, ext:'webp'},
      { youtube: "fPLhA7vSMIQ", title: "Fascia a jógában 7. Funkcionális és karvonalak", id: 87, ext:'webp'},

      { youtube: "L-C42n7AH6I", title: "Újévi áramlás - kilégzés", id: 88, ext:'webp'},
      { youtube: "BrEYkGKoFPs", title: "Újévi áramlás - belégzés", id: 89, ext:'webp'},
      { youtube: "Dx3veVV8l30", title: "Újévi áramlás - csakraflow", id: 90, ext:'webp'},
      { youtube: "9fsoHWck74Y", title: "Újévi áramlás - slow-flow", id: 91, ext:'webp'},
      { youtube: "-aSb7YTsg2s", title: "Újévi áramlás - szemgyakorlás", id: 92, ext:'webp'},
      { youtube: "f5JilO7CR6M", title: "Újévi áramlás - távolítók", id: 93, ext:'webp'},

      { youtube: "BYTKLmeMOvc", title: "Égi erő - áldás slowflow", id: 94, ext:'webp'},
      { youtube: "PCUTqE97EfI", title: "Életút -  slowflow", id: 95, ext:'webp'},
      { youtube: "9wUMd6nYlyY", title: "Hála - slowflow", id: 96, ext:'webp'},
      { youtube: "NrCMJQrjr2U", title: "Belső erő - slowflow", id: 97, ext:'webp'},
      { youtube: "y8glV_SVjpk", title: "Hold gyakorlás - slowflow", id: 98, ext:'webp'},
      { youtube: "aZL-wJXTXFA", title: "Nyugalom - slowflow", id: 99, ext:'webp'},
      { youtube: "ylIsVTv9_sI", title: "Csúcsászanák 1: parivrtta koundinyászana", id: 100, ext:'webp'},
      { youtube: "CSDGnC8TmYI", title: "Csúcsászanák 2: astavakrászana", id: 101, ext:'webp'},
      { youtube: "PTQndKxTzwE", title: "Csúcsászanák 3: kézenállás", id: 103, ext:'webp'},
      { youtube: "UHwqiTsZ8xE", title: "Csúcsászanák 4: spárga", id: 104, ext:'webp'},
      { youtube: "eJGFig1ATZ8", title: "Csúcsászanák 5: zászló", id: 105, ext:'webp'},
      { youtube: "QTLP022m4bg", title: "Csúcsászanák 6. Híd", id: 106, ext:'webp'},
      { youtube: "tGTLIKwMPpU", title: "Flow-time 1 Ganesha gyakorlás", id: 107, ext:'webp'},
      { youtube: "WfTb3ALTVjo", title: "Flow-time 2 alkarállás", id: 108, ext:'webp'},
      { youtube: "IP9p4WQtcu8", title: "Flow-time 3 szeretet flow", id: 109, ext:'webp'},
      { youtube: "QIjoLwhBgS8", title: "Flow-time 4 yin-yang flow", id: 110, ext:'webp'},
      { youtube: "NjDR-GEzVgw", title: "Flow-time 5 yin-flow", id: 111, ext:'webp'},
      { youtube: "4bZtrCcIeg4", title: "Flow-time 6 paradicsommadár", id: 112, ext:'webp'},
      { youtube: "1yDksvXLBMc", title: "Stabilitás flow", id: 113, ext:'webp'},
      { youtube: "HfxOeAZpCEg", title: "Bátorság flow", id: 114, ext:'webp'},
      { youtube: "1bC_a4SipE0", title: "Békés harcos flow", id: 115, ext:'webp'},
      { youtube: "dcyB-wFPRDk", title: "Kamatkarászana", id: 116, ext:'webp'},
      { youtube: "-kit2bO4Cro", title: "Szamakónászana flow", id: 117, ext:'webp'},
      { youtube: "g5ArJznKdDc", title: "Fókusz - figyelem", id: 118, ext:'webp'},
      { youtube: "cLofVB7Fri4", title: "Fókusz - nyitottság", id: 119, ext:'webp'},
      { youtube: "ljJu-95tG9s", title: "Fókusz - Lélek fénye", id: 120, ext:'webp'},
      { youtube: "Y5GWp0N6nB8", title: "Fókusz - Jelenlét", id: 121, ext:'webp'},
      { youtube: "s7yZN0JOq-c", title: "Fókusz - földelj", id: 122, ext:'webp'},
      { youtube: "pe4PwUNZhf4", title: "Morning flow - hála", id: 123, ext:'webp'},
      { youtube: "CkR5YLtgfCU", title: "Morning flow - energia", id: 124, ext:'webp'},
      { youtube: "lUfvdVvkjg0", title: "Morning flow - jelenlét", id: 125, ext:'webp'},
      { youtube: "nGXFynbr-Ns", title: "Morning flow - teremtés", id: 126, ext:'webp'},
      { youtube: "0Js7R_n9w0", title: "Morning flow - üdvözletek", id: 127, ext:'webp'},
    ].reverse())

    // regexp '.[^']+'
    .map((item) => ({ ...item, title: `${item.id}. ${item.title}` })),
  tabor: [
    "1.webp",
    "2.webp",
    "3.webp",
    "5.webp",
    "6.webp",
    "7.webp",
    "8.webp",
    "4.webp",
  ],
  fasciaFlowList: [
    { title: "1. Lélegző fascia - mini újrahangolás 11'", youtube: "iI2jLQmxuiU", id: 128, ext:'webp'},
    { title: "2. Fascia flow - áramlásba érkezés 21'", youtube: "jZj6vhC2exc", id: 129, ext:'webp'},
    { title: "3. Belső tér kinyitása - Teljes fascia átmozgatás 42'", youtube: "pvO6zwRIPd4", id: 130, ext:'webp'},
    { title: "4. Test-lélek mély regeneráló flow 33'", youtube: "QQNH3pYVdik", id: 131, ext:'webp'},
    { title: "5. Gyökértől a gerincig fascia flow 42'", youtube: "ml53xdD84vs", id: 132, ext:'webp'},
    { title: "6. Fascia lift - könnyedség és erő (fejenállással) 19'", youtube: "wkiMXpfYJ5U", id: 133, ext:'webp'},
    { title: "7. Fascia - egy kis elmélet", youtube: "NWyTmTldqxU", id: 134, ext:'jpg'},
  ],
};
